function n_rho = normalize_density(s,cmpd)
% For each sample, normalizes the density of a compound by the maximum
% density
% Inputs
    % s - Structure generated by loading .mat file created by pdeScript.m
    % or modelExtension.m
    % cmpd - Compound identifier. Integer from 1 to 6.
        % cmpd = 1 ~ [B]
        % cmpd = 2 ~ [R]
        % cmpd = 3 ~ [C]
        % cmpd = 4 ~ [hb]
        % cmpd = 5 ~ [Hb]
        % cmpd = 6 ~ [B]+[C]
% Outputs
    % n_rho - Normalized matrix of densities
n_rho = s.M(:,:,cmpd)./max(s.M(:,:,cmpd));
end

