function x_list = x_boundary(s,cmpd,thresh)
% Returns a list of points with normalized densities closest to threshold
% value
% Inputs
    % s - Structure generated by loading .mat file created by pdeScript.m
    % or modelExtension.m
    % cmpd - Compound identifier. Integer from 1 to 6.
        % cmpd = 1 ~ [B]
        % cmpd = 2 ~ [R]
        % cmpd = 3 ~ [C]
        % cmpd = 4 ~ [hb]
        % cmpd = 5 ~ [Hb]
        % cmpd = 6 ~ [B]+[C]
    % thresh - Normalized density value between 0 and 1
% Outputs
    % x_list - List of points with normalized densities closest to
    % threshold value
    
% Normalize density matrix
rho = normalize_density(s,cmpd);
% Locate positions of points with normalized densities closest to threshold
% value
x_list = s.x(abs(rho-thresh) == min(abs(rho-thresh)));
end

